### PR TITLE
Fix#28/handle structs as params

### LINKED ISSUE #28: Xcribe breaks when Date struct is given as params
The solution for me was to convert the Date struct to `iso8601`.

Maybe we could mimic the behaviour from plug when processing that test, it was implicitly converting the date to a string format. Also, I don't know but we could in some way improve our error handling, helping the user to find the offender code, in this case, I had to search between all the tests the one that was passing a date directly, the stack trace from xcribe helped me identify the problem but not the part of the code that was causing it.

Example of test:

```elixir
base_date = Date.utc_today()
second_date = Date.add(base_date, -3)

params = %{
  "payments" => [
    %{"date" => second_date},
    %{"date" => base_date}
  ]
}

body = %{"data" => params}
path = Routes.reclaiming_path(conn, :update, reclaiming_id)

assert %{"errors" => errors} =
          conn
          |> with_access_token()
          |> patch(path, body)
          |> document()
          |> json_response(:unprocessable_entity)
```

Stacktrace
```
** (EXIT from #PID<0.94.0>) exited in: GenServer.stop(#PID<0.1878.0>, :normal, :infinity)
    ** (EXIT) exited in: :sys.terminate(#PID<0.1878.0>, :normal, :infinity)
        ** (EXIT) an exception was raised:
            ** (Protocol.UndefinedError) protocol Enumerable not implemented for ~D[2020-05-04] of type Date (a struct). This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.PrepareStream, DBConnection.Stream, Scrivener.Page, IO.Stream, List, Function, HashDict, Map, GenEvent.Stream, File.Stream, HashSet, MapSet, Range, Stream, Date.Range
                (elixir 1.10.1) lib/enum.ex:1: Enumerable.impl_for!/1
                (elixir 1.10.1) lib/enum.ex:141: Enumerable.reduce/3
                (elixir 1.10.1) lib/enum.ex:3383: Enum.reduce/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:288: Xcribe.Swagger.Formatter.schema_add_properties/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:298: anonymous fn/3 in Xcribe.Swagger.Formatter.reduce_properties/2
                (stdlib 3.12.1) maps.erl:232: :maps.fold_1/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:288: Xcribe.Swagger.Formatter.schema_add_properties/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:283: Xcribe.Swagger.Formatter.schema_add_items/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:298: anonymous fn/3 in Xcribe.Swagger.Formatter.reduce_properties/2
                (stdlib 3.12.1) maps.erl:232: :maps.fold_1/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:288: Xcribe.Swagger.Formatter.schema_add_properties/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:298: anonymous fn/3 in Xcribe.Swagger.Formatter.reduce_properties/2
                (stdlib 3.12.1) maps.erl:232: :maps.fold_1/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:288: Xcribe.Swagger.Formatter.schema_add_properties/3
                (xcribe 0.3.0) lib/swagger/formatter.ex:205: Xcribe.Swagger.Formatter.media_type_object/2
                (xcribe 0.3.0) lib/swagger/formatter.ex:189: Xcribe.Swagger.Formatter.path_item_object_add_request_body/2
                (xcribe 0.3.0) lib/swagger/formatter.ex:46: Xcribe.Swagger.Formatter.path_item_object_from_request/1
                (xcribe 0.3.0) lib/swagger/swagger.ex:45: Xcribe.Swagger.paths_object_func/2
                (elixir 1.10.1) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
                (xcribe 0.3.0) lib/swagger/swagger.ex:25: Xcribe.Swagger.mount_data_in_raw_object/2

```

### PR DESCRIPTION
**Pull request by Danielwsx64**
## Motivation

Fix #28 

Solves #19 with another approach. Since we implemented #36, Xcribe handle some parsing errors. Now we have a general validator that meet the #19 proposal, that is validate requests before trying to write the doc.

## Proposed solution

- Create a module to validate the `Request` struct data.
- Ensure request params hasn't structs.
- Output an error message for requests with structs
image

This solution was discussed in #51

### CODE REVIEW

File: test/xcribe/request/validator_test.exs [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+    test "return an error when request has a struct in path_params" do
+      meta = %{metadata: "value"}
+      request = %Request{path_params: ~D[2021-02-15], __meta__: meta}
+
+      assert Validator.validate(request) ==
+               {:error,
+                %Error{
+                  type: :validation,
+                  message:
+                    "The Plug.Conn params must be valid HTTP params. A struct Elixir.Date was found!",
```
Comment (thiamsantos) [inline test/xcribe/request/validator_test.exs:42]:
```suggestion
                    "The Plug.Conn params must be valid HTTP params. A struct Date was found!",
```

@Danielwsx64 Do you think would be nicer for the user to remove the Elixir prefix?

File: lib/xcribe/request/validator.ex [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+    request
+    |> Map.fetch!(key)
+    |> find_struct()
+    |> handle_validate_params(request)
+  end
+
+  def find_struct(%{__struct__: module}) do
+    %Error{
+      type: :validation,
+      message: "The Plug.Conn params must be valid HTTP params. A struct #{module} was found!"
```
Comment (thiamsantos) [inline lib/xcribe/request/validator.ex:26]: @Danielwsx64 Would be possible to include the path to the struct found in the params? Sometimes is hard to find the place where the struct is been returned.

Would make sense to include it on xcribe, or is better to let the user debug the test to find it?

File: test/xcribe/request/validator_test.exs (hunk 1 above)
Comment (Danielwsx64) [reply test/xcribe/request/validator_test.exs]: Done :v:

File: lib/xcribe/request/validator.ex (hunk 2 above)
Comment (Danielwsx64) [reply lib/xcribe/request/validator.ex]: I believe the request params are built in test setup section. It supposed to be easy find out where you added an struct to params. Any way I can't figure out how to point the path for the struct. If you have a suggestion for a easy way to do that we could add.

Comment (thiamsantos) [reply lib/xcribe/request/validator.ex]: > If you have a suggestion for a easy way to do that we could add.

An easy way, I don't have. I think we could accumulate the step took for each iteration in the recursion. 

But thinking better, seems to be a little out of scope of xcribe to provide this path.

**Review by thiamsantos — APPROVED** [review]

File: lib/xcribe/request/validator.ex [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+  defp validate_parameters_in({:error, _err} = error, _key), do: error
+
+  defp validate_parameters_in({:ok, request}, key) do
+    request
+    |> Map.fetch!(key)
+    |> find_struct()
+    |> handle_validate_params(request)
+  end
+
+  def find_struct(%{__struct__: module}) do
```
Comment (antedeguemon) [inline lib/xcribe/request/validator.ex:23]:
```suggestion
  defp find_struct(%{__struct__: module}) do
```

**Review by antedeguemon — APPROVED** [review]

File: lib/xcribe/request/validator.ex (hunk 3 above)
Comment (Danielwsx64) [reply lib/xcribe/request/validator.ex:23]: @antedeguemon tks :v:
