### PR TITLE
Fix#49/handle plug upload struct

### LINKED ISSUE #49: Support Plug.Upload struct
In a test we are simulating a file upload sending a Plug.Upload to the app. However xcribe breaks trying to decode the `%Plug.Upload{}` struct.

Test:

```elixir
file = %Plug.Upload{
  filename: "my_app_logo.jpg",
  path: "test/fixtures/my_app_logo.jpg",
  content_type: "image/jpeg"
}

params = %{
  "file" => file
}

body = %{"data" => params}
path = Routes.file_path(conn, :create)

assert %{"data" => data} =
         conn
         |> post(path, body)
         |> document()
         |> json_response(:created)
```

Exception:
```
Randomized with seed 889537
  [ Xcribe ] Exception
┃
┃ [E] →  An exception was raised. Elixir.Protocol.UndefinedError
┃        > test POST /cases/:case_id/files creates file_upload
┃        test/my_app_web/controllers/file_controller_test.exs:46
┃
┃        |> document()
┃           ^^^^^^^^
┃

 - Exception stacktrace:

** (Protocol.UndefinedError) protocol Enumerable not implemented for %Plug.Upload{content_type: "image/jpeg", filename: "my_app_logo.jpg", path: "test/fixtures/my_app_logo.jpg"} of type Plug.Upload (a struct). This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.PrepareStream, DBConnection.Stream, Floki.HTMLTree, Scrivener.Page, IO.Stream, List, Function, HashDict, Map, GenEvent.Stream, File.Stream, HashSet, MapSet, Range, Stream, Date.Range
    (elixir 1.10.1) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.10.1) lib/enum.ex:141: Enumerable.reduce/3
    (elixir 1.10.1) lib/enum.ex:3383: Enum.reduce/3
    (xcribe 0.7.3) lib/xcribe/json_schema.ex:68: Xcribe.JsonSchema.schema_add_properties/3
    (xcribe 0.7.3) lib/xcribe/json_schema.ex:78: anonymous fn/3 in Xcribe.JsonSchema.reduce_properties/2
    (stdlib 3.12.1) maps.erl:232: :maps.fold_1/3
    (xcribe 0.7.3) lib/xcribe/json_schema.ex:68: Xcribe.JsonSchema.schema_add_properties/3
    (xcribe 0.7.3) lib/xcribe/json_schema.ex:78: anonymous fn/3 in Xcribe.JsonSchema.reduce_properties/2
    (stdlib 3.12.1) maps.erl:232: :maps.fold_1/3
    (xcribe 0.7.3) lib/xcribe/json_schema.ex:68: Xcribe.JsonSchema.schema_add_properties/3
    (xcribe 0.7.3) lib/xcribe/api_blueprint/formatter.ex:59: Xcribe.ApiBlueprint.Formatter.request_object/1
    (xcribe 0.7.3) lib/xcribe/api_blueprint/formatter.ex:48: Xcribe.ApiBlueprint.Formatter.action_object/1
    (xcribe 0.7.3) lib/xcribe/api_blueprint/formatter.ex:36: Xcribe.ApiBlueprint.Formatter.resource_object/1
    (xcribe 0.7.3) lib/xcribe/api_blueprint/formatter.ex:24: Xcribe.ApiBlueprint.Formatter.full_request_object/1
    (xcribe 0.7.3) lib/xcribe/api_blueprint/api_blueprint.ex:24: Xcribe.ApiBlueprint.format_and_merge/2
    (elixir 1.10.1) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (xcribe 0.7.3) lib/xcribe/api_blueprint/api_blueprint.ex:17: Xcribe.ApiBlueprint.apib_struct/1
    (xcribe 0.7.3) lib/xcribe/api_blueprint/api_blueprint.ex:9: Xcribe.ApiBlueprint.generate_doc/1
    (xcribe 0.7.3) lib/xcribe/formatter.ex:49: Xcribe.Formatter.handle_cast/2
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
```

### PR DESCRIPTION
**Pull request by Danielwsx64**
## Motivation

Fix #49 

## Proposed solution
Translate `Plug.Upload` to docs specifications

Swagger: https://swagger.io/docs/specification/describing-request-body/multipart-requests/
ApiBlueprint uses raw request body

### CODE REVIEW

File: lib/xcribe/swagger/formatter.ex [hunk 1]
```diff
@@ -188,14 +189,32 @@ defmodule Xcribe.Swagger.Formatter do
...
   end
 
+  defp add_enconding_if_needed(schema, _content), do: schema
+
+  defp enconding_for(%Upload{} = upload, schema, property) do
+    schema_encoding = Map.get(schema, :encoding, %{})
+
+    new_encoding = Map.merge(schema_encoding, %{property => %{contentType: upload.content_type}})
+
+    Map.put(schema, :encoding, new_encoding)
```
Comment (thiamsantos) [inline lib/xcribe/swagger/formatter.ex:213]:
```
Map.update(schema, :encoding, %{}, fn encoding -> Map.merge(encoding, %{property => %{contentType: upload.content_type}}) end)
```

WDYT about using Map.update?

**Review by thiamsantos — APPROVED** [review]

File: lib/xcribe/swagger/formatter.ex (hunk 1 above)
Comment (Danielwsx64) [reply lib/xcribe/swagger/formatter.ex]: Done :v: (with some adjusts)
